# Generated by Django 3.2.6 on 2021-09-17 13:56
"""Alter question and end date migrations of the polls."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for the polls."""

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(null=True,
                                       verbose_name='date time ended'),
        ),
    ]
